# Generated by Django 3.0.7 on 2020-06-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200619_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
