# Generated by Django 3.0.7 on 2020-06-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_items_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='OrderNo',
            field=models.IntegerField(),
        ),
    ]
