# Generated by Django 3.0.7 on 2020-06-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orders_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Item',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
